from app.forms.aeronave_form import AeronaveForm
from app.forms.aeroporto_form import AeroportoForm
from app.forms.cartao_form import CartaoForm
from app.forms.cidade_form import CidadeForm
from app.forms.companhia_form import CompanhiaForms
from app.forms.destino_form import DestinoForm
from app.forms.horario_form import HorarioForm
from app.forms.modelo_aeronave_form import ModeloAeronaveForm
from app.forms.origem_form import OrigemForm
from app.forms.pagamento_form import PagamentoForm
from app.forms.pais_form import PaisForm
from app.forms.passageiro_form import PassageiroForm
from app.forms.passagem_form import PassagemForm
from app.forms.reserva_form import ReservaForm
from app.forms.reserva_passageiro_form import ReservaPassageiroForm 
from app.forms.trecho_form import TrechoForm